<a href="https://colab.research.google.com/github/SunnyDahitJ/ML-programs/blob/main/lab3_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split 

In [33]:
df = pd.read_csv("Crop_recommendation.csv")
x = df.temperature
y = df.label
print(df)

x = [[i] for i in list(x)]
# y = [[i] for i in list(y)]

print(x)
print(y)
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.30, shuffle= True)


        N   P   K  temperature   humidity        ph    rainfall   label
0      90  42  43    20.879744  82.002744  6.502985  202.935536    rice
1      85  58  41    21.770462  80.319644  7.038096  226.655537    rice
2      60  55  44    23.004459  82.320763  7.840207  263.964248    rice
3      74  35  40    26.491096  80.158363  6.980401  242.864034    rice
4      78  42  42    20.130175  81.604873  7.628473  262.717340    rice
...   ...  ..  ..          ...        ...       ...         ...     ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

[2200 rows x 8 columns]
[[20.87974371], [21.77046169], [23.00445915], [26.49109635], [20.13017482], [23.05804872], [22.70883798], [20.2

In [34]:
KNeighborsClassifier(
    n_neighbors=5,          # The number of neighbours to consider
    weights='uniform',      # How to weight distances
    algorithm='auto',       # Algorithm to compute the neighbours
    leaf_size=30,           # The leaf size to speed up searches
    p=1,                    # The power parameter for the Minkowski metric
    metric='euclidian',     # The type of distance to use
    metric_params=None,     # Keyword arguments for the metric function
    n_jobs=None             # How many parallel jobs to run
)


clf = KNeighborsClassifier()
clf.fit(X_train, y_train.values.ravel())


KNeighborsClassifier()

In [35]:
predictions = clf.predict(X_test)
print(predictions)

['coffee' 'papaya' 'chickpea' 'mothbeans' 'mungbean' 'mungbean' 'banana'
 'chickpea' 'jute' 'banana' 'mango' 'maize' 'cotton' 'grapes' 'watermelon'
 'banana' 'jute' 'banana' 'coconut' 'kidneybeans' 'apple' 'mango'
 'mungbean' 'mango' 'muskmelon' 'apple' 'banana' 'grapes' 'chickpea'
 'banana' 'pigeonpeas' 'papaya' 'apple' 'apple' 'cotton' 'chickpea'
 'kidneybeans' 'blackgram' 'mango' 'mothbeans' 'banana' 'blackgram'
 'apple' 'lentil' 'mothbeans' 'mungbean' 'jute' 'banana' 'blackgram'
 'maize' 'kidneybeans' 'coconut' 'banana' 'rice' 'coffee' 'coconut'
 'coffee' 'kidneybeans' 'pomegranate' 'chickpea' 'mothbeans' 'apple'
 'papaya' 'apple' 'rice' 'kidneybeans' 'apple' 'apple' 'chickpea' 'banana'
 'muskmelon' 'apple' 'coffee' 'kidneybeans' 'banana' 'orange'
 'pomegranate' 'kidneybeans' 'jute' 'maize' 'mango' 'cotton' 'maize'
 'coconut' 'banana' 'jute' 'chickpea' 'cotton' 'mango' 'banana' 'cotton'
 'apple' 'apple' 'apple' 'banana' 'kidneybeans' 'apple' 'blackgram'
 'pigeonpeas' 'papaya' 'blac

In [36]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, predictions))

0.18333333333333332


In [37]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions))

[[14  0  0  0  0  1  6  1  3  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  7  3  0  5  1  1  0  2  0  0  0  0  1  2  4  0  0  1  0  0  0]
 [ 0  3  9  0  0  2  0  0  0  0  0  1  2  3  2  2  1  1  1  0  0  0]
 [ 0  0  0 23  0  0  0  1  0  4  1  0  0  0  0  0  0  0  0  2  2  0]
 [ 0  8  1  0  3  2  4  0  2  0  0  0  0  1  3  5  0  0  2  0  0  1]
 [ 4  3  1  0  6  2  3  0  1  1  2  2  1  1  2  0  0  0  0  0  0  0]
 [18  0  1  0  1  2  5  0  4  0  1  1  0  0  0  0  0  0  0  0  0  1]
 [ 2  0  1  4  0  2  0  5  0  4  0  1  3  1  1  0  3  3  1  1  0  0]
 [ 5  2  1  0  6 11  3  0  2  0  1  3  0  1  0  0  0  0  0  0  0  3]
 [ 5  0  0 11  0  0  0  1  1  8  1  3  0  0  0  0  0  0  0  0  3  1]
 [ 2  1  1  3  2  2  1  0  1  1  0  1  1  0  2  5  0  0  0  3  0  1]
 [ 5  0  0  5  2  2  0  1  0  2  0  0  0  0  0  0  0  0  0  2  1  1]
 [ 0  3  7  0  1  0  0  1  0  0  0  0  5  5  2  1  2  1  1  0  0  0]
 [ 0  3  2  0  1  1  0  0  2  0  0  2  3  3  5  2  0  0  1  0  0  0]
 [ 0  9  3  0  2  1  0  0  0  0  0